In [2]:
import torch

In [8]:
w = torch.tensor([1.],requires_grad = True)
x = torch.tensor([2.], requires_grad = True)

a = x+w
# a.retain_grad() # 可以通过.retain_grad()来保留非任意节点的梯度值。
b = w+1
y = a*b

v = y.backward()
print(w)
print(w.grad) # tensor([5.])
# y 对 w的微分 等于y通过a对w的微分加上y通过x对w的微分的和
# dy/dw = dy/da * da/dw + dy/dx * dx/dw =2×w+x+1=5

tensor([1.], requires_grad=True)
tensor([5.])


In [9]:
# 这个图中的叶子节点，是w和x，是整个计算图的根基。之所以用叶子节点的概念，是为了减少内存，在反向传播结束之后，非叶子节点的梯度会被释放掉
print(w.is_leaf,x.is_leaf,a.is_leaf,b.is_leaf,y.is_leaf)
print(w.grad,x.grad,a.grad,b.grad,y.grad)

True True False False False
tensor([5.]) tensor([2.]) None None None


/Users/tyler/anaconda/envs/tf2/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
# torch.tensor有一个属性grad_fn,grad_fn的作用是记录创建该张量时所用的函数，这个属性反向传播的时候会用到。
# 例如在上面的例子中，y.grad_fn=MulBackward0,表示y是通过乘法得到的。所以求导的时候就是用乘法的求导法则。
# 同样的，a.grad=AddBackward0表示a是通过加法得到的，使用加法的求导法则。
print(y.grad_fn)
print(a.grad_fn)
print(w.grad_fn) # 叶子节点的.grad_fn是None

None
