In [51]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


/Users/tyler/anaconda/lib/python3.6/site-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['random']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [2]:
set_printoptions(precision=2,suppress='True')

In [3]:
a = linspace(0,12,100).astype(float)

In [4]:
a.reshape(2,-1)

array([[ 0.  ,  0.12,  0.24,  0.36,  0.48,  0.61,  0.73,  0.85,  0.97,
         1.09,  1.21,  1.33,  1.45,  1.58,  1.7 ,  1.82,  1.94,  2.06,
         2.18,  2.3 ,  2.42,  2.55,  2.67,  2.79,  2.91,  3.03,  3.15,
         3.27,  3.39,  3.52,  3.64,  3.76,  3.88,  4.  ,  4.12,  4.24,
         4.36,  4.48,  4.61,  4.73,  4.85,  4.97,  5.09,  5.21,  5.33,
         5.45,  5.58,  5.7 ,  5.82,  5.94],
       [ 6.06,  6.18,  6.3 ,  6.42,  6.55,  6.67,  6.79,  6.91,  7.03,
         7.15,  7.27,  7.39,  7.52,  7.64,  7.76,  7.88,  8.  ,  8.12,
         8.24,  8.36,  8.48,  8.61,  8.73,  8.85,  8.97,  9.09,  9.21,
         9.33,  9.45,  9.58,  9.7 ,  9.82,  9.94, 10.06, 10.18, 10.3 ,
        10.42, 10.55, 10.67, 10.79, 10.91, 11.03, 11.15, 11.27, 11.39,
        11.52, 11.64, 11.76, 11.88, 12.  ]])

In [5]:
a

array([ 0.  ,  0.12,  0.24,  0.36,  0.48,  0.61,  0.73,  0.85,  0.97,
        1.09,  1.21,  1.33,  1.45,  1.58,  1.7 ,  1.82,  1.94,  2.06,
        2.18,  2.3 ,  2.42,  2.55,  2.67,  2.79,  2.91,  3.03,  3.15,
        3.27,  3.39,  3.52,  3.64,  3.76,  3.88,  4.  ,  4.12,  4.24,
        4.36,  4.48,  4.61,  4.73,  4.85,  4.97,  5.09,  5.21,  5.33,
        5.45,  5.58,  5.7 ,  5.82,  5.94,  6.06,  6.18,  6.3 ,  6.42,
        6.55,  6.67,  6.79,  6.91,  7.03,  7.15,  7.27,  7.39,  7.52,
        7.64,  7.76,  7.88,  8.  ,  8.12,  8.24,  8.36,  8.48,  8.61,
        8.73,  8.85,  8.97,  9.09,  9.21,  9.33,  9.45,  9.58,  9.7 ,
        9.82,  9.94, 10.06, 10.18, 10.3 , 10.42, 10.55, 10.67, 10.79,
       10.91, 11.03, 11.15, 11.27, 11.39, 11.52, 11.64, 11.76, 11.88,
       12.  ])

In [6]:
a.dtype

dtype('float64')

In [7]:
a.itemsize

8

In [8]:
a = zeros((3,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
a = ones((3,2),dtype=int8)
a

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [10]:
a.dtype

dtype('int8')

In [80]:
a=random.randint(1,11,12)
a

array([ 2,  3,  4,  9,  4,  7,  1,  8, 10,  1,  6,  1])

In [83]:
a=a.reshape(3,2,2)

In [84]:
a

array([[[ 2,  3],
        [ 4,  9]],

       [[ 4,  7],
        [ 1,  8]],

       [[10,  1],
        [ 6,  1]]])

In [85]:
a.sum(axis=0)

array([[16, 11],
       [11, 18]])

In [89]:
a[:,:,:1]

array([[[ 2],
        [ 4]],

       [[ 4],
        [ 1]],

       [[10],
        [ 6]]])

In [90]:
a*a

array([[[  4,   9],
        [ 16,  81]],

       [[ 16,  49],
        [  1,  64]],

       [[100,   1],
        [ 36,   1]]])