In [100]:
import tensorflow as tf
from tensorflow.keras.layers import Dropout,Flatten,Dense
from tensorflow.keras.models import Sequential
import numpy as np

In [101]:
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255, x_test/255

In [102]:
model = Sequential([
    Flatten(input_shape = (28,28)),
    Dense(128,activation="relu"),
    Dropout(0.2),
    Dense(10)
])

In [103]:
prediction = model(x_train[:1]).numpy()
prediction

array([[ 0.39725667, -0.3244596 , -0.08850849,  0.2153718 ,  0.10499106,
         0.6291433 , -0.827528  ,  0.08103852, -0.13066149, -0.13936271]],
      dtype=float32)

In [104]:
tf.nn.softmax(prediction).numpy()

array([[0.14006263, 0.06805889, 0.0861702 , 0.11676984, 0.10456659,
        0.17661572, 0.04115334, 0.10209171, 0.08261336, 0.08189765]],
      dtype=float32)

In [105]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [106]:
loss_fn(y_train[:1], predictions).numpy()

2.2586234

In [107]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [108]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2947 - accuracy: 0.9141
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1425 - accuracy: 0.9566
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1053 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0857 - accuracy: 0.9745
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0735 - accuracy: 0.9770


In [113]:
model.evaluate(x_test,  y_test, verbose=2)
# 输出loss和accuracy

313/313 - 0s - loss: 0.0719 - accuracy: 0.9770


[0.07185598462820053, 0.9769999980926514]

In [110]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [111]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.2121450e-08, 2.3389296e-10, 3.2284681e-06, 7.3630268e-05,
        4.1975707e-09, 1.0160888e-06, 7.7401349e-14, 9.9991357e-01,
        5.8478707e-07, 7.8441863e-06],
       [9.7502016e-07, 1.0467056e-04, 9.9967408e-01, 2.1342858e-04,
        2.6329982e-14, 3.3902199e-06, 1.6310250e-07, 8.2844764e-12,
        3.2991520e-06, 3.3986309e-13],
       [1.8053715e-06, 9.9835217e-01, 7.8030971e-05, 4.7159779e-06,
        7.4449570e-05, 5.5135552e-05, 5.6439389e-05, 1.1935630e-03,
        1.8248455e-04, 1.3107880e-06],
       [9.9877602e-01, 2.1891525e-10, 1.0494584e-03, 6.3707853e-07,
        1.0915503e-05, 2.1678712e-05, 1.4111773e-05, 5.3939606e-05,
        3.7443792e-06, 6.9437403e-05],
       [4.0038785e-07, 4.2303519e-10, 1.2988283e-05, 5.6850551e-09,
        9.9901533e-01, 6.8011268e-08, 6.9887278e-06, 6.5250577e-05,
        1.4299577e-06, 8.9745090e-04]], dtype=float32)>

In [114]:
model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[ -7.044201  , -10.99207   ,  -1.4594154 ,   1.6676333 ,
         -8.104673  ,  -2.6154628 , -19.005686  ,  11.184001  ,
         -3.1679304 ,  -0.5716503 ],
       [ -2.9721029 ,   1.7040119 ,  10.868379  ,   2.4164965 ,
        -20.399363  ,  -1.7259114 ,  -4.760183  , -14.647934  ,
         -1.7531409 , -17.84153   ],
       [ -6.6467    ,   6.5763955 ,  -2.88036   ,  -5.68651   ,
         -2.9273436 ,  -3.2276711 ,  -3.2042987 ,  -0.15276776,
         -2.0308    ,  -6.9668374 ],
       [  7.4179206 , -14.823191  ,   0.55966437,  -6.8472276 ,
         -4.0061812 ,  -3.3200343 ,  -3.7493556 ,  -2.4085002 ,
         -5.076109  ,  -2.1559398 ],
       [ -5.026811  , -11.879544  ,  -1.5474415 ,  -9.2814045 ,
          9.703036  ,  -6.799571  ,  -2.1671906 ,   0.06674588,
         -3.7538443 ,   2.688069  ]], dtype=float32)>