In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'1.14.0'

pb 是 protocol buffer的缩写 是Google提供的一种数据序列化协议
是一种轻便高效的结构化数据存储格式，可以用于结构化数据序列化，很适合做数据存储或 RPC 数据交换格式。它可用于通讯协议、数据存储等领域的语言无关、平台无关、可扩展的序列化结构数据格式。

# 矩阵乘法 零矩阵 ones constant range linspace

In [4]:
# w and x are variables, y is operation
tensor = tf.Variable([[1,2,3],[4,5,6]]) # 是不是variable形式的tensor都可以
w = tf.Variable([[18,3,1],[6,5,4]])
x = tf.Variable([[3],[5],[7]])
y = tf.matmul(w,x)
# global_variables_initializer() is to do initalization for all the variables
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print(y.eval())
# print(w)

# 形式很接近numpy
# 格式以float32为主
t1 = tf.zeros([3,4],tf.int32) # [[0,0,0,0],[0,0,0,0],[0,0,0,0]]
# tensor = tf.Variable([[1,2,3],[4,5,6]])
t2 = tf.zeros_like(tensor) # [[0 0 0], [0 0 0]]
t3 = tf.ones([2,4],tf.float32) # [[1. 1. 1. 1.],[1. 1. 1. 1.]]
t4 = tf.ones_like(tensor) # [[1 1 1],[1 1 1]]
y = t2+tensor
print(t3)
with tf.Session() as sess:
    print(t3.eval())
    print(t4.eval())
    sess.run(tf.global_variables_initializer()) # 当有运算的时候必须初始化,不是运算可以直接在sess中.eval()
    print(y.eval())
    

m1=tf.constant([[4,3]],tf.int32,name = 'first_value')
m2=tf.constant([[2],[3]],tf.int32)
m3=tf.constant(-1.0, shape=[2,3]) # [[-1. -1. -1.],[ -1. -1. -1.]]
m3 = tf.constant("Guru", tf.string)
m4 = tf.zeros(10)
m4=tf.linspace(10.0, 12.0, 3, name="linspace") # [10.0 11.0 12.0]
m5=tf.range(3, 18, 3) # [3,6,9,12,15]
product = tf.matmul(m1,m2)

with tf.Session() as sess:  # can also be sess =tf.Session()
    result = sess.run(product) # this method is to run a specific operation
    print(result)
    sess.run(tf.global_variables_initializer()) # this method is to run all the operations
    print(sess.run(m2))
    print(t2)


[[76]
 [71]]
Tensor("ones:0", shape=(2, 4), dtype=float32)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[[1 2 3]
 [4 5 6]]
[[17]]
[[2]
 [3]]
Tensor("zeros_like:0", shape=(2, 3), dtype=int32)


# Variable 和 get_variable

In [5]:
with tf.variable_scope("one"):
    a = tf.get_variable("one",  [1])
with tf.variable_scope("one",reuse = True):
    b = tf.get_variable("one", [1])

W1206 22:28:45.966649 4459296192 deprecation.py:506] From /Users/tyler/anaconda/envs/tylertf/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [6]:
var3 = tf.Variable(3.,dtype=tf.float32,name="var2")
print(var3.name)
value = [0, 1, 2, 3, 4]
init = tf.constant_initializer(value)
var4 = tf.get_variable("var4",[5],dtype=tf.float32,initializer=tf.constant_initializer(1.0))
var5 = tf.get_variable("var5",[5],dtype=tf.float32,initializer=init)
# value = np.array(value)
# value = value.reshape([2, 4])
init = tf.constant_initializer(value)
print(var4.name)

var2:0
var4:0


In [7]:
init = tf.global_variables_initializer() # prepare to initialize all variables
with tf.Session() as sess:
    init.run() # Initialize x and z
    sess.run(var3)
    print(var3.eval())
    print(var4.eval())
    print(var5.eval())
# 
    

3.0
[1. 1. 1. 1. 1.]
[0. 1. 2. 3. 4.]


# 正态分布随机+shuffle

In [8]:
norm = tf.random_normal([2,3],mean=-1, stddev=4)

# shuffle the first dimension of a tensor
c = tf.constant([[1,2],[3,4],[5,6]])
shuff = tf.random_shuffle(c)

#Each time we run these ops, different results are generated
sess = tf.Session()
print(sess.run(norm))
print(sess.run(shuff))


[[-1.293839    0.02465451  5.0543985 ]
 [ 3.039198   -0.9453696  -4.6017265 ]]
[[5 6]
 [1 2]
 [3 4]]


# 加法迭代更新

###### 这个加法看上去很复杂,但是其实不论是简单的计算还是复杂如forward propagation,可能代码量都差不多

In [9]:
state = tf.Variable(0)
new_value = tf.add(state, tf.constant(1))
update = tf.assign(state, new_value)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


 # Saver

 ###### 这个saver到用到的时候可能比较好理解

In [10]:
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]])
y = tf.matmul(w,x)
init_op = tf.global_variables_initializer()
saver =tf.train.Saver()
with tf.Session() as sess:
    sess.run(init_op)
        # do some work with the model.
        # save the variables to disk.
    save_path = saver.save(sess,"/Users/tyler/PycharmProjects/Tensorflow/model")
    print("Model saved in file:", save_path)

Model saved in file: /Users/tyler/PycharmProjects/Tensorflow


# numpy 形式 convert to tensor

In [13]:
import numpy as np
a =np.zeros((3,3))
ta = tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(ta))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
output = tf.multiply(input1, input2)
with tf.Session() as sess:
    print(sess.run([output],feed_dict={input1:[7.],input2:[2.]}))

[array([14.], dtype=float32)]
