# tf.newaxis

tf.newaxis 和np.newaxis的效果和功能是一样的 所以以下无论是np.newaxis还是tf.newaxis的讲解 理论上都是一样的
就是插入在哪个维度就在原shape那个位置加一个1，matrix就会被reshape成那个样子

In [7]:
import numpy as np
#原始数据集维度
data = np.arange(25).reshape((5,5))
print(data)
print("original",data.shape)

#np.newaxis用在第一维度
data_1 = data[np.newaxis,:]
print(data_1)
print("used in first dimension",data_1.shape)

#np.newaxis放在第二个参数位置
data_2 = data[:,np.newaxis,] # 或者data[:,np.newaxis,...] 或者 data[:,np.newaxis]
print(data_2)
print("used in seocnd dimension",data_2.shape)

#np.newaxis放在第三个参数位置
data_3 = data[:,...,np.newaxis]
print(data_3)
print("used in third dimension",data_3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
original (5, 5)
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]]
used in first dimension (1, 5, 5)
[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]

 [[15 16 17 18 19]]

 [[20 21 22 23 24]]]
used in seocnd dimension (5, 1, 5)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]
  [13]
  [14]]

 [[15]
  [16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]
  [24]]]
used in third dimension (5, 5, 1)


用none的效果和np.newaxis一样
...是省略所有的冒号来用省略号代替,大家看这个a[:, :, None]和a[…, None]的输出是一样的，就是因为…代替了前面两个冒号