In [18]:
import numpy as np
import tensorflow as tf

In [5]:
a = np.random.rand(3,4)
a

array([[0.59741766, 0.41700158, 0.88638552, 0.23387888],
       [0.01298054, 0.16994025, 0.97542113, 0.26772503],
       [0.81981457, 0.6782283 , 0.54408843, 0.04136951]])

In [8]:
b = a[...,np.newaxis]
b

array([[[0.59741766],
        [0.41700158],
        [0.88638552],
        [0.23387888]],

       [[0.01298054],
        [0.16994025],
        [0.97542113],
        [0.26772503]],

       [[0.81981457],
        [0.6782283 ],
        [0.54408843],
        [0.04136951]]])

In [17]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a, op_flags=['readwrite']):
    print(x)
    x[...] = 2 * x

0
1
2
3
4
5


In [16]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
dataset = tf.data.Dataset.from_tensor_slices(np.random.uniform(size=(5,2)))
print(dataset)

<TensorSliceDataset shapes: (2,), types: tf.float64>
